// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA6Hd1wimOsQ-NOavqHdv5ZRm-SmtjRyv0',
    appId: '1:455510626901:web:30a1d246d897fd5bf83adc',
    messagingSenderId: '455510626901',
    projectId: 'minorproject-5d3f2',
    authDomain: 'minorproject-5d3f2.firebaseapp.com',
    storageBucket: 'minorproject-5d3f2.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBgjIvcJ5XBY_gYKHT0q74PfKP0RxMDDKg',
    appId: '1:455510626901:android:1c8a8a16cbc95935f83adc',
    messagingSenderId: '455510626901',
    projectId: 'minorproject-5d3f2',
    storageBucket: 'minorproject-5d3f2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyApvqSjshNgKyAG65VG4mWIxWYbPKKjd-c',
    appId: '1:455510626901:ios:4bf3d7fa2f4ddbdcf83adc',
    messagingSenderId: '455510626901',
    projectId: 'minorproject-5d3f2',
    storageBucket: 'minorproject-5d3f2.firebasestorage.app',
    iosBundleId: 'com.example.minorproject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyApvqSjshNgKyAG65VG4mWIxWYbPKKjd-c',
    appId: '1:455510626901:ios:4bf3d7fa2f4ddbdcf83adc',
    messagingSenderId: '455510626901',
    projectId: 'minorproject-5d3f2',
    storageBucket: 'minorproject-5d3f2.firebasestorage.app',
    iosBundleId: 'com.example.minorproject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA6Hd1wimOsQ-NOavqHdv5ZRm-SmtjRyv0',
    appId: '1:455510626901:web:3f6ca8cb055ead2af83adc',
    messagingSenderId: '455510626901',
    projectId: 'minorproject-5d3f2',
    authDomain: 'minorproject-5d3f2.firebaseapp.com',
    storageBucket: 'minorproject-5d3f2.firebasestorage.app',
  );
}
